name: "Set Assignee"
on:
  issue_comment:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["Workflow"]'
          assignees: '["jason683"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
